openapi: "3.0.2"

info:
    title: "API для Yandex Guide"
    version: "1.0"

servers:
    -   url: http://51.250.39.97:8080/guide/v1/

components:

    schemas:
        Error:
            $ref: "./schemas/Error.yaml"

        Coordinates:
            $ref: "./schemas/Coordinates.yaml"

        Restaurant:
            $ref: "./schemas/Restaurant.yaml"

        RestaurantFilter:
            $ref: "./schemas/RestaurantFilter.yaml"

        Selection:
            $ref: "./schemas/Selection.yaml"

        Scores:
            $ref: "./schemas/Scores.yaml"


    parameters:
        PathUUID:
            $ref: "./params/PathUUID.yaml"

    securitySchemes:
        UserTicketAuth:
            type: apiKey
            in: header
            name: Authorization



paths:
    /restaurants:
        $ref: "./paths/restaurants.yaml"
    /restaurant/{id}:
        $ref: "./paths/restaurant_by_id.yaml"
    /selections:
        $ref: "./paths/selections.yaml"
    /selection/{id}:
        $ref: "./paths/selection_by_id.yaml"
    /ml-sort:
        $ref: "./paths/ml-sort.yaml"
    /ml-rate:
        $ref: "./paths/ml-rate.yaml"
