openapi: "3.0.2"

info:
    title: "API для Yandex Guide"
    version: "1.0"

servers:
    -   url: http://51.250.39.97:8080/guide/v1/

tags:
    - name: Рестораны
    - name: Подборки
    - name: ML

components:

    schemas:
        Error:
            $ref: "./schemas/Error.yaml"

        Coordinates:
            $ref: "./schemas/Coordinates.yaml"

        Restaurant:
            $ref: "./schemas/Restaurant.yaml"

        RestaurantFilter:
            $ref: "./schemas/RestaurantFilter.yaml"

        Selection:
            $ref: "./schemas/Selection.yaml"

        Scores:
            $ref: "./schemas/Scores.yaml"

        CollectionCreate:
            $ref: "./schemas/CollectionCreate.yaml"

        InsertIntoCollection:
            $ref: "./schemas/InsertIntoCollection.yaml"

    parameters:
        PathUUID:
            $ref: "./params/PathUUID.yaml"

    securitySchemes:
        UserTicketAuth:
            type: apiKey
            in: header
            name: Authorization

paths:
    /restaurants:
        $ref: "./paths/restaurants.yaml"
        tags:
            - Рестораны

    /restaurants/{id}:
        $ref: "./paths/restaurant_by_id.yaml"
        tags:
            - Рестораны

    /selections:
        $ref: "./paths/selections.yaml"
        tags:
            - Подборки
    /selections/{id}:
        $ref: "./paths/selection_by_id.yaml"
        tags:
            - Подборки
    /collection:
        $ref: "./paths/create_collection.yaml"
        tags:
            - Подборки
    /collection/{id}:
        $ref: "./paths/insert_into_collection.yaml"
        tags:
            - Подборки

    /ml-rate:
        $ref: "./paths/ml-rate.yaml"
        tags:
            - ML
