openapi: "3.0.2"
info:
    title: API для Гида
    version: "1.0"
servers:
    -   url: http://51.250.39.97:8080/

components:

     responses:
         UnauthorizedError:
             description: X-Ya-User-Ticket key is missing or invalid
    securitySchemes:
        UserTicketAuth:
            type: apiKey
            in: header
            name: Authorization
paths:

    /guide/v1/selections:


    /guide/v1/selections/{id}:

    /guide/v1:

