openapi: "3.0.2"
info:
    title: API для Гида
    version: "1.0"
servers:
    -   url: http://localhost:8080/
components:
    schemas:
        coordinates:
            type: object
            properties:
                lat:
                    description: Latitude
                    type: number
                    format: double
                lon:
                    description: Longitude
                    type: number
                    format: double
            required:
                - lat
                - lon
        restaurant:
            type: object
            properties:
                id: 
                    type: string
                coordinates:
                    $ref: "#/components/schemas/coordinates"
                name:
                    type: string
                description:
                    type: string
                address:
                    type: string
                is_approved:
                    type: boolean
                rating:
                    type: number
                    format: double
                price_lower_bound:
                    type: integer
                price_upper_bound:
                    type: integer
                tags:
                    type: object
                    properties:
                        items:
                            type: array
                            items:
                                type: string
                is_favorite:
                    type: boolean
            required:
                - id
                - coordinates
                - name
                - description
                - address
                - is_public
                - rating
                - check

    # responses:
    #     UnauthorizedError:
    #         description: X-Ya-User-Ticket key is missing or invalid
    # securitySchemes:
    #     UserTicketAuth:
    #         type: apiKey
    #         in: header
    #         name: X-Ya-User-Ticket
paths:
    /guide/v1/restaurants:
        get:
            description: Get recommended establishments in the area
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                lower_left_corner:
                                    description: coordinates
                                    $ref: "#/components/schemas/coordinates"
                                top_right_corner:
                                    description: coordinates
                                    $ref: "#/components/schemas/coordinates"
                                max_count:
                                    type: integer
                                user_id:
                                    type: integer
                            required:
                                - coordinates
                                - max_count
                                - user_id
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/restaurant'
                '400':
                    description: invalid input parameters
                '401':
                    description: unauthorized