openapi: "3.0.2"
info:
    title: API для Гида
    version: "1.0"
servers:
    -   url: http://51.250.39.97:8080/
components:
    schemas:
        coordinates:
            type: object
            properties:
                lat:
                    description: Latitude
                    type: number
                    format: double
                lon:
                    description: Longitude
                    type: number
                    format: double
            required:
                - lat
                - lon
        restaurant:
            type: object
            properties:
                id: 
                    type: string
                    format: uuid
                coordinates:
                    $ref: "#/components/schemas/coordinates"
                name:
                    type: string
                description:
                    type: string
                address:
                    type: string
                is_approved:
                    type: boolean
                rating:
                    type: number
                    format: double
                price_lower_bound:
                    type: integer
                price_upper_bound:
                    type: integer
                tags:
                    type: array
                    items:
                        type: string
                            
                is_favorite:
                    type: boolean
            required:
                - id
                - coordinates
                - name
                - description
                - address
                - is_public
                - rating
                - price_lower_bound
                - price_upper_bound
                - tags
                - is_favorite
        selection:
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                name:
                    type: string
                description:
                    type: string
                is_public:
                    type: short    
            required:
                - id
                - name
                - description            

    # responses:
    #     UnauthorizedError:
    #         description: X-Ya-User-Ticket key is missing or invalid
    securitySchemes:
        UserTicketAuth:
            type: apiKey
            in: header
            name: Authorization
paths:
    /guide/v1/restaurants:
        post:
            description: Get recommended establishments in the area
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                lower_left_corner:
                                    description: coordinates
                                    $ref: "#/components/schemas/coordinates"
                                top_right_corner:
                                    description: coordinates
                                    $ref: "#/components/schemas/coordinates"
                                max_count:
                                    type: integer
                            required:
                                - coordinates
            security:
                -   UserTicketAuth: [ ]
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/restaurant'
                '400':
                    description: invalid input parameters
                '401':
                    description: unauthorized
    /guide/v1/restaurant/{id}:
        get:
            description: Get restaurant by id
            parameters:
                - in: path
                  name: id
                  required: true
                  description: uuid of the user to get.
                  schema:
                    type: string
            security:
                -   UserTicketAuth: [ ]
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/restaurant'
                '400':
                    description: invalid input parameters
                '401':
                    description: unauthorized                
                                                  
    /guide/v1/selections:
        get:
            summary: Получение всех подборок
            description: Возвращает список всех подборок.
            responses:
                '200':
                    description: Успешное получение списка подборок.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/selection'
                '500':
                    description: Внутренняя ошибка сервера.
<<<<<<< HEAD

=======
                    
>>>>>>> selections
    /guide/v1/selections/{id}:
         get:
            summary: Получить список всех заведений в подборке
            description: Возвращает список всех заведений, относящихся к заданной подборке
            parameters:
                - name: selectionId
                  in: path
                  required: true
                  schema:
                    type: string
                    format: uuid
                  description: Идентификатор подборки в формате UUID
            responses:
                '200':
                    description: Успешное получение списка подборок.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/restaurant'
                '400':
                    description: Неверный запрос
                '404':
                    description: Подборка не найдена
                '500':
                    description: Внутренняя ошибка сервера
    /guide/v1/ml:
        post:
            description: Sort restaurants ids list by ML (mock)
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                restaurant_ids:
                                    description: List of restaurant ids
                                    type: array
                                    items: {
                                        type: integer
                                    }
                            required:
                                - restaurant_ids
            security:
                - UserTicketAuth: [ ]
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    restaurant_ids:
                                        type: array
                                        items: {
                                            type: integer
                                        }
                '400':
                    description: invalid input parameters
                '401':
                    description: unauthorized



   