openapi: "3.0.2"
info:
    title: API для Гида
    version: "1.0"
servers:
    -   url: http://localhost:8080/
components:
    schemas:
        coordinates:
            type: object
            properties:
                lat:
                    description: Latitude
                    type: number
                    format: double
                lon:
                    description: Longitude
                    type: number
                    format: double
            required:
                - lat
                - lon
        institution:
            type: object
            properties:
                id: 
                    type: integer
                coordinates:
                    $ref: "#/components/schemas/coordinates"
                name:
                    type: string
                description:
                    type: string
                address:
                    type: string
                is_public:
                    type: boolean
                rating:
                    type: number
                    format: double
                check:
                    type: number
                    format: double

    # responses:
    #     UnauthorizedError:
    #         description: X-Ya-User-Ticket key is missing or invalid
    # securitySchemes:
    #     UserTicketAuth:
    #         type: apiKey
    #         in: header
    #         name: X-Ya-User-Ticket
paths:
    /recommendations:
        get:
            description: Get recommended establishments in the area
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                coordinates:
                                    description: coordinates
                                    $ref: "#/components/schemas/coordinates"
                            required:
                                - coordinates

            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/institution'
                # '401':
                #     $ref: "#/components/responses/UnauthorizedError"