openapi: "3.0.2"
info:

    title: API для Гида
    version: "1.0"
servers:
    -   url: http://localhost:8080/
components:
    schemas:
        coordinates:
            type: object
            properties:
                lat:
                    description: Latitude
                    type: number
                    format: double
                lon:
                    description: Longitude
                    type: number
                    format: double
            required:
                - lat
                - lon
        institution:
            type: object
            properties:
                id: 
                    type: integer
                coordinates:
                    $ref: "#/components/schemas/coordinates"
                name:
                    type: string
                description:
                    type: string
                address:
                    type: string
                approved:
                    type: boolean
                rating:
                    type: number
                    format: double
                check:
                    type: number
                    format: double
                price_lower_bound:
                    type: integer
                price_upper_bound:
                    type: integer
            required:
                - id
                - coordinates
                - name
                - description
                - address
                - is_public
                - rating
                - check
        selection:
            type: object
            properties:
                id:
                    type: integer
                name:
                    type: string
                description:
                    type: string
                is_public:
                    type: boolean    
            required:
                - id
                - name
                - description        

    # responses:
    #     UnauthorizedError:
    #         description: X-Ya-User-Ticket key is missing or invalid
    # securitySchemes:
    #     UserTicketAuth:
    #         type: apiKey
    #         in: header
    #         name: X-Ya-User-Ticket
paths:
    /recommendations:
        get:
            description: Get recommended establishments in the area
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                lower_left_corner:
                                    description: coordinates
                                    $ref: "#/components/schemas/coordinates"
                                top_right_corner:
                                    description: coordinates
                                    $ref: "#/components/schemas/coordinates"
                                max_count:
                                    type: integer
                                user_id:
                                    type: integer
                            required:
                                - coordinates
                                - max_count
                                - user_id
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/institution'
                '400':
                    description: invalid input parameters

    # /guide/v1/selections:
    #     get:
    #         summary: Получение всех подборок
    #         description: Возвращает список всех подборок.
    #         responses:
    #             '200':
    #             description: Успешное получение списка подборок.
    #             content:
    #                 application/json:
    #                         schema:
    #                             type: object
    #                             properties:
    #                                 items:
    #                                     type: array
    #                                     items:
    #                                         $ref: '#/components/schemas/selection'
    #             '500':
    #             description: Внутренняя ошибка сервера.           
    
    /guide/v1/selections:
        get:
            summary: Получение всех подборок
            description: Возвращает список всех подборок.
            responses:
                '200':
                description: Успешное получение списка подборок.
                content:
                    application/json:
                    schema:
                        type: array
                        items:
                        type: object
                        properties:
                            id:
                            type: integer
                            example: 1
                            name:
                            type: string
                            example: "Популярные места"
                            description:
                            type: string
                            example: "Список популярных мест в городе."
                '500':
                description: Внутренняя ошибка сервера.     
